services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "9002:9002"

  proxy:
    image: nginx:latest
    ports:
      - "${PORT_PROXY}:${PORT_PROXY}"
    volumes:
      - ./${DIR_PROXY}/nginx.conf:/etc/nginx/conf.d/default.conf